name: First_Workflow
on: push
jobs:
  task1:
    runs-on: windows-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Print Something
        run: python GH_Actions.py
  task2:
    runs-on: ubuntu-latest
    steps:
      - name: Get the Code
        uses: actions/checkout@v4
      - name: Print the Output
        run: python3 GH_Actions.py

